In [1]:
import numpy as np 
import pandas as pd 
from mlxtend.frequent_patterns import apriori, association_rules

In [2]:
poi_data = pd.read_csv('../Datasets/Task 1/POIdata_cityC.csv')
categories = pd.read_csv('../Datasets/Task 1/POI_datacategories.csv', header=None)

In [3]:
poi_data['grid_id'] = poi_data['x'].astype(str) + "_" + poi_data['y'].astype(str)
grid_baskets = poi_data.groupby('grid_id')['category'].apply(list)

for basket in grid_baskets:
    basket = list(set(basket))

grid_baskets

grid_id
101_200                                        [74]
102_188                                        [18]
108_161                                    [80, 81]
109_162                                        [48]
10_105                                     [80, 76]
                             ...
9_197      [48, 76, 47, 59, 53, 69, 79, 58, 54, 63]
9_4                                            [73]
9_5                    [61, 82, 66, 41, 73, 69, 72]
9_6                                            [62]
9_90                                           [74]
Name: category, Length: 3251, dtype: object

In [4]:
one_hot_list = []

for i in range(len(grid_baskets)):
    row = []
    for j in range(len(categories)):
        row.append(0)
    one_hot_list.append(row)


for basket_index in range(len(grid_baskets)):
    for category_index in grid_baskets[basket_index]:
        one_hot_list[basket_index][category_index-1] = 1

one_hot_df = pd.DataFrame(one_hot_list, columns=categories[0])
one_hot_df

C:\Users\User1\AppData\Local\Temp\ipykernel_46988\2041592903.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  for category_index in grid_baskets[basket_index]:

,Food,Shopping,Entertainment,Japanese restaurant,Western restaurant,Eat all you can restaurant,Chinese restaurant,Indian restaurant,Ramen restaurant,Curry restaurant,...,Accountant Office,IT Office,Publisher Office,Building Material,Gardening,Heavy Industry,NPO,Utility Copany,Port,Research Facility
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,1,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3246,0,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
3247,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3248,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3249,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3250,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
grid_baskets_df = grid_baskets.reset_index()
grid_baskets_df.columns = ['grid_id', 'categories']
print(grid_baskets_df)

      grid_id                                categories
0     101_200                                      [74]
1     102_188                                      [18]
2     108_161                                  [80, 81]
3     109_162                                      [48]
4      10_105                                  [80, 76]
...       ...                                       ...
3246    9_197  [48, 76, 47, 59, 53, 69, 79, 58, 54, 63]
3247      9_4                                      [73]
3248      9_5              [61, 82, 66, 41, 73, 69, 72]
3249      9_6                                      [62]
3250     9_90                                      [74]

[3251 rows x 2 columns]

In [6]:
grid_baskets_df = grid_baskets_df.join(one_hot_df)
grid_baskets_df.drop(['categories'], axis='columns', inplace=True)
grid_baskets_df.set_index('grid_id', inplace=True)
grid_baskets_df

,Food,Shopping,Entertainment,Japanese restaurant,Western restaurant,Eat all you can restaurant,Chinese restaurant,Indian restaurant,Ramen restaurant,Curry restaurant,...,Accountant Office,IT Office,Publisher Office,Building Material,Gardening,Heavy Industry,NPO,Utility Copany,Port,Research Facility
grid_id,,,,,,,,,,,,,,,,,,,,,
101_200,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
102_188,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108_161,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,1,0,0,0,0
109_162,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10_105,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9_197,0,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
9_4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9_5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
9_6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9_90,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
freq_items = apriori(grid_baskets_df, min_support=0.25, use_colnames=True)

rules = association_rules(
    freq_items, metric="lift", min_threshold=1, num_itemsets=len(grid_baskets)
)
rules = rules.sort_values(["confidence", "lift"], ascending=[False, False])
print(rules.head())

                          antecedents        consequents  antecedent support  \
182   (Hair Salon, Building Material)  (Transit Station)            0.271301
158         (Real Estate, Hair Salon)  (Transit Station)            0.285451
164  (Real Estate, Accountant Office)  (Transit Station)            0.278376
146  (Real Estate, Elderly Care Home)  (Transit Station)            0.272224
20                         (Hospital)  (Transit Station)            0.301446

     consequent support   support  confidence      lift  representativity  \
182            0.571516  0.255306    0.941043  1.646572               1.0
158            0.571516  0.267302    0.936422  1.638487               1.0
164            0.571516  0.258382    0.928177  1.624060               1.0
146            0.571516  0.252230    0.926554  1.621220               1.0
20             0.571516  0.278683    0.924490  1.617608               1.0

     leverage  conviction  zhangs_metric   jaccard  certainty  kulczynski
182  0.100253    7.267740       0.538875  0.434555   0.862406    0.693880
158  0.104163    6.739538       0.545352  0.453312   0.851622    0.702065
164  0.099286    5.965809       0.532492  0.436817   0.832378    0.690138
146  0.096650    5.833968       0.526509  0.426417   0.828590    0.683944
20   0.106402    5.674512       0.546562  0.468944   0.823773    0.706055

c:\Users\User1\anaconda3\envs\dm-proj2\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

### Top frequent itemsets
and verification of support values

In [8]:
freq_itemsets_copy = freq_items.copy()

# Calculate the support counts manually and add as a new column
support_counts = []
for index, row in freq_itemsets_copy.iterrows():
    itemset = list(row["itemsets"])  # convert frozenset of items to list
    items = one_hot_df[itemset]  # get the columns in the itemset
    mask = items.all(
        axis=1
    )  # check if all items in the itemset are present in each row (grid cell)
    support_count = mask.sum() / len(one_hot_df)
    support_counts.append(support_count)

freq_itemsets_copy["check_support"] = support_counts
# sort the dataframe by the support count and reset the index

freq_itemsets_copy = freq_itemsets_copy.sort_values(
    "support", ascending=False
).reset_index(drop=True)

freq_itemsets_copy.head()

    support             itemsets  check_support
0  0.571516    (Transit Station)       0.571516
1  0.482621               (Park)       0.482621
2  0.472778  (Building Material)       0.472778
3  0.434943    (Home Appliances)       0.434943
4  0.426946     (Heavy Industry)       0.426946

In [9]:
# save to csv
freq_itemsets_copy.to_csv("../Datasets/Task 1/freq_itemsets_cityC.csv")

### Top Association Rules by Lift

In [10]:
# keep only antecedents, consequents and lift
rulesC = rules.copy()[["antecedents", "consequents", "lift"]]
# combine antecedents and consequents into a rule column with this format: (antecedents) -> (consequents)
rule_col = (
    rulesC["antecedents"].apply(lambda x: ", ".join(list(x)))
    + " -> "
    + rulesC["consequents"].apply(lambda x: ", ".join(list(x)))
)
# insert rule column into df
rulesC.insert(0, "rule", rule_col)
# drop antecedents and consequents
rulesC.drop(["antecedents", "consequents"], axis="columns", inplace=True)
# sort by lift and reset index
rulesC = rulesC.sort_values("lift", ascending=False).reset_index(drop=True)

In [11]:
rulesC.head()

                                         rule      lift
0  Hair Salon -> Real Estate, Transit Station  2.242471
1  Real Estate, Transit Station -> Hair Salon  2.242471
2             Hair Salon -> Real Estate, Park  2.215365
3             Real Estate, Park -> Hair Salon  2.215365
4             Real Estate -> Hair Salon, Park  2.187702

In [12]:
# save to csv
rulesC.to_csv("../Datasets/Task 1/rules_cityC.csv")